version: '3.8'
services:
    server:
        build: .
        restart: always
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
        volumes:
            - .:/var/manfred
        command: yarn dev

    db:
        image: postgres
        ports:
            - '5432:${DB_PORT}'
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}

volumes:
    data: {}
