# Installs Node.js image
FROM node:16.13.1-alpine3.14

# sets the working directory for any RUN, CMD, COPY command
# all files we put in the Docker container running the server will be in /usr/src/app (e.g. /usr/src/app/package.json)
WORKDIR /usr/src/app

# Copies package.json, package-lock.json, tsconfig.json, .env to the root of WORKDIR
COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./
# temporary solution
COPY .env.template ./  
COPY init_db.sh ./

# Copies everything in the src directory to WORKDIR/src
COPY ./src ./src

# Installs all packages
RUN yarn install

EXPOSE 3000

# Runs the dev yarn script to build & start the server
CMD yarn dev
